/**
 * Domain contract.
 *
 * This file is the single source of truth for the shape of a plan. The SPA, the
 * serverless API, and the validation schemas all import from here. Changing a
 * type here forces the compiler to flag every consumer — that is the point.
 *
 * Rule: treat edits to this file as load-bearing. They require review, because a
 * casual change ripples through all four features (plan, grocery, subs, budget).
 *
 * Money is stored in integer minor units (cents). Never use floats for currency.
 */

export type MealType = 'breakfast' | 'lunch' | 'dinner';

export type IngredientCategory =
  | 'produce'
  | 'dairy'
  | 'meat'
  | 'pantry'
  | 'frozen'
  | 'bakery'
  | 'beverages'
  | 'other';

export type Unit = 'g' | 'kg' | 'ml' | 'l' | 'tsp' | 'tbsp' | 'cup' | 'piece' | 'pinch';

export type SubstitutionReason = 'allergy' | 'cost' | 'availability' | 'preference';

export type DietaryRestriction =
  | 'vegetarian'
  | 'vegan'
  | 'gluten-free'
  | 'dairy-free'
  | 'nut-free'
  | 'halal'
  | 'kosher'
  | 'pescatarian';

export interface Ingredient {
  id: string;
  name: string;
  quantity: number;
  /** Null for countable items where the count lives in `quantity` (e.g. 3 eggs). */
  unit: Unit | null;
  category: IngredientCategory;
  /** Cost per unit in cents. Null when no trusted price is available. */
  unitCostCents: number | null;
  /** True when the cost came from a model estimate rather than a price source. */
  costIsEstimated: boolean;
}

export interface Meal {
  id: string;
  type: MealType;
  title: string;
  steps: string[];
  prepMinutes: number;
  ingredients: Ingredient[];
  /** When true, regeneration leaves this meal untouched. */
  locked: boolean;
}

export interface Substitution {
  id: string;
  ingredientId: string;
  replacementName: string;
  reason: SubstitutionReason;
  /** Change in total cost if accepted. Negative means it saves money. */
  costDeltaCents: number;
  note: string | null;
}

export interface Preferences {
  /** ISO date. Single day for the MVP; a range arrives in Phase 4. */
  date: string;
  householdSize: number;
  budgetCapCents: number;
  dietaryRestrictions: DietaryRestriction[];
  /** Free-text allergens, kept separate from structured restrictions. */
  allergies: string[];
  cuisinePreferences: string[];
  maxPrepMinutes: number | null;
  /** Items the user already has; planning should prefer using these. */
  pantryItems: string[];
}

export interface Plan {
  id: string;
  /** Null for an anonymous, client-only plan (no account required). */
  userId: string | null;
  preferences: Preferences;
  meals: Meal[];
  substitutions: Substitution[];
  createdAt: string;
  updatedAt: string;
}

/* ------------------------------------------------------------------ */
/* Derived views. These are NEVER stored or generated by the model.   */
/* They are computed from `Plan` (see derive.ts). This is what lets    */
/* the four features compose from one generation instead of four.      */
/* ------------------------------------------------------------------ */

export interface GroceryLineItem {
  name: string;
  category: IngredientCategory;
  quantity: number;
  unit: Unit | null;
  totalCostCents: number | null;
  costIsEstimated: boolean;
  /** Which ingredient rows rolled up into this line. */
  ingredientIds: string[];
}

export interface GroceryList {
  items: GroceryLineItem[];
  byCategory: Partial<Record<IngredientCategory, GroceryLineItem[]>>;
}

export interface BudgetBreakdown {
  capCents: number;
  totalCents: number;
  remainingCents: number;
  isOverBudget: boolean;
  /** True if any line used an estimated price — surface this in the UI. */
  hasEstimates: boolean;
  byMeal: Array<{ mealId: string; title: string; costCents: number }>;
  byCategory: Array<{ category: IngredientCategory; costCents: number }>;
}
